using Seevalocal.Core.Models;
using System.Text;

namespace Seevalocal.Config.Export;

/// <summary>
/// Serializes a <see cref="ResolvedConfig"/> into a reproducible shell script
/// (bash or PowerShell) that runs the Seevalocal executable with all chosen settings.
/// The script does NOT manually start llama-server - Seevalocal manages that internally.
/// </summary>
public sealed class ShellScriptExporter
{
    /// <summary>
    /// Produces a shell script string for the given config and target shell dialect.
    /// The script runs Seevalocal with all settings as CLI arguments.
    /// </summary>
    public static string Export(ResolvedConfig config, ShellTarget target)
    {
        return target switch
        {
            ShellTarget.Bash => ExportBash(config),
            ShellTarget.PowerShell => ExportPowerShell(config),
            _ => throw new ArgumentOutOfRangeException(nameof(target), target, null),
        };
    }

    // -------------------------------------------------------------------------
    // Bash
    // -------------------------------------------------------------------------

    private static string ExportBash(ResolvedConfig config)
    {
        var sb = new StringBuilder();
        var ts = DateTimeOffset.UtcNow.ToString("yyyy-MM-ddTHH:mm:ssZ");

        _ = sb.AppendLine("#!/usr/bin/env bash");
        _ = sb.AppendLine("# Generated by Seevalocal");
        _ = sb.AppendLine($"# Timestamp: {ts}");
        _ = sb.AppendLine("# This script runs Seevalocal with all settings. llama-server is managed internally.");
        _ = sb.AppendLine();

        var args = new List<string>();

        // Server options
        if (config.Server.Manage == true)
        {
            args.Add("--manage");
            if (config.Server.Model is { Kind: ModelSourceKind.LocalFile } model && !string.IsNullOrEmpty(model.FilePath))
                args.Add($"--model-file {EscapeBash(model.FilePath)}");
            else if (config.Server.Model is { Kind: ModelSourceKind.HuggingFace } hf && !string.IsNullOrEmpty(hf.HfRepo))
                args.Add($"--hf-repo {EscapeBash(hf.HfRepo)}");
        }
        else
        {
            args.Add("--no-manage");
            if (!string.IsNullOrEmpty(config.Server.BaseUrl))
                args.Add($"--server-url {EscapeBash(config.Server.BaseUrl)}");
        }

        var url = new Uri(config.Server.BaseUrl ?? "http://127.0.0.1:8080");
        if (url != null)
        {
            args.Add($"--host {EscapeBash(url.Host)}");
            args.Add($"--port {url.Port}");
        }
        if (!string.IsNullOrEmpty(config.Server.ApiKey))
            args.Add($"--api-key {EscapeBash(config.Server.ApiKey)}");

        // llama-server tuning options
        var llama = config.LlamaServer;
        if (llama.ContextWindowTokens.HasValue)
            args.Add($"--ctx {llama.ContextWindowTokens}");
        if (llama.BatchSizeTokens.HasValue)
            args.Add($"--batch {llama.BatchSizeTokens}");
        if (llama.UbatchSizeTokens.HasValue)
            args.Add($"--ubatch {llama.UbatchSizeTokens}");
        if (llama.ParallelSlotCount.HasValue)
            args.Add($"--parallel {llama.ParallelSlotCount}");
        if (llama.GpuLayerCount.HasValue)
            args.Add($"--ngl {llama.GpuLayerCount}");
        if (llama.EnableFlashAttention.HasValue)
            args.Add(llama.EnableFlashAttention.Value ? "--flash-attn" : "--no-flash-attn");
        if (llama.EnableCachePrompt.HasValue)
            args.Add(llama.EnableCachePrompt.Value ? "--cache-prompt" : "--no-cache-prompt");
        if (llama.EnableContextShift.HasValue)
            args.Add(llama.EnableContextShift.Value ? "--context-shift" : "--no-context-shift");
        if (!string.IsNullOrEmpty(llama.KvCacheTypeK))
            args.Add($"--kv-type-k {EscapeBash(llama.KvCacheTypeK)}");
        if (!string.IsNullOrEmpty(llama.KvCacheTypeV))
            args.Add($"--kv-type-v {EscapeBash(llama.KvCacheTypeV)}");
        if (llama.ThreadCount.HasValue)
            args.Add($"--threads {llama.ThreadCount}");
        if (llama.SamplingTemperature.HasValue)
            args.Add($"--temp {llama.SamplingTemperature}");
        if (llama.TopP.HasValue)
            args.Add($"--top-p {llama.TopP}");
        if (llama.TopK.HasValue)
            args.Add($"--top-k {llama.TopK}");
        if (llama.MinP.HasValue)
            args.Add($"--min-p {llama.MinP}");
        if (llama.Seed.HasValue)
            args.Add($"--seed {llama.Seed}");
        if (!string.IsNullOrEmpty(llama.ChatTemplate))
            args.Add($"--chat-template {EscapeBash(llama.ChatTemplate)}");
        if (!string.IsNullOrEmpty(llama.ReasoningFormat))
            args.Add($"--reasoning-format {EscapeBash(llama.ReasoningFormat)}");
        if (llama.LogVerbosity.HasValue)
            args.Add($"--log-verbosity {llama.LogVerbosity}");

        // Eval options
        if (config.DataSource is { } ds)
        {
            if (!string.IsNullOrEmpty(ds.FilePath))
                args.Add($"--data-file {EscapeBash(ds.FilePath)}");
            if (!string.IsNullOrEmpty(ds.PromptDirectory))
                args.Add($"--prompt-dir {EscapeBash(ds.PromptDirectory)}");
            if (!string.IsNullOrEmpty(ds.ExpectedDirectory))
                args.Add($"--expected-dir {EscapeBash(ds.ExpectedDirectory)}");
        }

        // Judge options
        if (config.Judge is { } judge)
        {
            if (!string.IsNullOrEmpty(judge.ServerConfig.BaseUrl))
                args.Add($"--judge-url {EscapeBash(judge.ServerConfig.BaseUrl)}");
            if (judge.ServerConfig.Model is { Kind: ModelSourceKind.LocalFile } judgeModel && !string.IsNullOrEmpty(judgeModel.FilePath))
                args.Add($"--judge-model-file {EscapeBash(judgeModel.FilePath)}");
            else if (judge.ServerConfig.Model is { Kind: ModelSourceKind.HuggingFace } judgeHf && !string.IsNullOrEmpty(judgeHf.HfRepo))
                args.Add($"--judge-hf-repo {EscapeBash(judgeHf.HfRepo)}");
            if (!string.IsNullOrEmpty(judge.ServerConfig.ApiKey))
                args.Add($"--judge-api-key {EscapeBash(judge.ServerConfig.ApiKey)}");
            if (!string.IsNullOrEmpty(judge.JudgePromptTemplate) && judge.JudgePromptTemplate != "standard")
                args.Add($"--judge-template {EscapeBash(judge.JudgePromptTemplate)}");
            if (judge.ScoreMinValue != 0)
                args.Add($"--judge-score-min {judge.ScoreMinValue}");
            if (judge.ScoreMaxValue != 10)
                args.Add($"--judge-score-max {judge.ScoreMaxValue}");
        }

        if (!string.IsNullOrEmpty(config.Run.PipelineName) && config.Run.PipelineName != "CasualQA")
            args.Add($"--pipeline {EscapeBash(config.Run.PipelineName)}");

        // Output options
        if (!string.IsNullOrEmpty(config.Run.OutputDirectoryPath) && config.Run.OutputDirectoryPath != "./results")
            args.Add($"--output-dir {EscapeBash(config.Run.OutputDirectoryPath)}");
        if (!string.IsNullOrEmpty(config.Run.RunName))
            args.Add($"--run-name {EscapeBash(config.Run.RunName)}");

        // Run control
        if (config.Run.MaxConcurrentEvals.HasValue)
            args.Add($"--max-concurrent {config.Run.MaxConcurrentEvals}");
        if (config.Run.ContinueOnEvalFailure == false)
            args.Add("--stop-on-failure");

        // Build the command
        _ = sb.AppendLine("# Run Seevalocal with all settings");
        _ = sb.AppendLine("seevalocal \\");
        foreach (var arg in args)
        {
            _ = sb.AppendLine($"  {arg} \\");
        }
        // Remove trailing backslash from last line
        var result = sb.ToString();
        if (result.EndsWith(" \\\n"))
            result = result[..^3] + "\n";

        return result;
    }

    // -------------------------------------------------------------------------
    // PowerShell
    // -------------------------------------------------------------------------

    private static string ExportPowerShell(ResolvedConfig config)
    {
        var sb = new StringBuilder();
        var ts = DateTimeOffset.UtcNow.ToString("yyyy-MM-ddTHH:mm:ssZ");

        _ = sb.AppendLine($"# Generated by Seevalocal. Run: {config.Run.RunName}");
        _ = sb.AppendLine($"# Timestamp: {ts}");
        _ = sb.AppendLine("# This script runs Seevalocal with all settings. llama-server is managed internally.");
        _ = sb.AppendLine();

        var args = new List<string>();

        // Server options
        if (config.Server.Manage == true)
        {
            args.Add("--manage");
            if (config.Server.Model is { Kind: ModelSourceKind.LocalFile } model && !string.IsNullOrEmpty(model.FilePath))
                args.Add($"--model-file {EscapePs(model.FilePath)}");
            else if (config.Server.Model is { Kind: ModelSourceKind.HuggingFace } hf && !string.IsNullOrEmpty(hf.HfRepo))
                args.Add($"--hf-repo {EscapePs(hf.HfRepo)}");
        }
        else
        {
            args.Add("--no-manage");
            if (!string.IsNullOrEmpty(config.Server.BaseUrl))
                args.Add($"--server-url {EscapePs(config.Server.BaseUrl)}");
        }

        var url = new Uri(config.Server.BaseUrl ?? "http://127.0.0.1:8080");
        if (url != null)
        {
            args.Add($"--host {EscapePs(url.Host)}");
            args.Add($"--port {url.Port}");
        }
        if (!string.IsNullOrEmpty(config.Server.ApiKey))
            args.Add($"--api-key {EscapePs(config.Server.ApiKey)}");

        // llama-server tuning options
        var llama = config.LlamaServer;
        if (llama.ContextWindowTokens.HasValue)
            args.Add($"--ctx {llama.ContextWindowTokens}");
        if (llama.BatchSizeTokens.HasValue)
            args.Add($"--batch {llama.BatchSizeTokens}");
        if (llama.UbatchSizeTokens.HasValue)
            args.Add($"--ubatch {llama.UbatchSizeTokens}");
        if (llama.ParallelSlotCount.HasValue)
            args.Add($"--parallel {llama.ParallelSlotCount}");
        if (llama.GpuLayerCount.HasValue)
            args.Add($"--ngl {llama.GpuLayerCount}");
        if (llama.EnableFlashAttention.HasValue)
            args.Add(llama.EnableFlashAttention.Value ? "--flash-attn" : "--no-flash-attn");
        if (llama.EnableCachePrompt.HasValue)
            args.Add(llama.EnableCachePrompt.Value ? "--cache-prompt" : "--no-cache-prompt");
        if (llama.EnableContextShift.HasValue)
            args.Add(llama.EnableContextShift.Value ? "--context-shift" : "--no-context-shift");
        if (!string.IsNullOrEmpty(llama.KvCacheTypeK))
            args.Add($"--kv-type-k {EscapePs(llama.KvCacheTypeK)}");
        if (!string.IsNullOrEmpty(llama.KvCacheTypeV))
            args.Add($"--kv-type-v {EscapePs(llama.KvCacheTypeV)}");
        if (llama.ThreadCount.HasValue)
            args.Add($"--threads {llama.ThreadCount}");
        if (llama.SamplingTemperature.HasValue)
            args.Add($"--temp {llama.SamplingTemperature}");
        if (llama.TopP.HasValue)
            args.Add($"--top-p {llama.TopP}");
        if (llama.TopK.HasValue)
            args.Add($"--top-k {llama.TopK}");
        if (llama.MinP.HasValue)
            args.Add($"--min-p {llama.MinP}");
        if (llama.Seed.HasValue)
            args.Add($"--seed {llama.Seed}");
        if (!string.IsNullOrEmpty(llama.ChatTemplate))
            args.Add($"--chat-template {EscapePs(llama.ChatTemplate)}");
        if (!string.IsNullOrEmpty(llama.ReasoningFormat))
            args.Add($"--reasoning-format {EscapePs(llama.ReasoningFormat)}");
        if (llama.LogVerbosity.HasValue)
            args.Add($"--log-verbosity {llama.LogVerbosity}");

        // Eval options
        if (config.DataSource is { } ds)
        {
            if (!string.IsNullOrEmpty(ds.FilePath))
                args.Add($"--data-file {EscapePs(ds.FilePath)}");
            if (!string.IsNullOrEmpty(ds.PromptDirectory))
                args.Add($"--prompt-dir {EscapePs(ds.PromptDirectory)}");
            if (!string.IsNullOrEmpty(ds.ExpectedDirectory))
                args.Add($"--expected-dir {EscapePs(ds.ExpectedDirectory)}");
        }

        // Judge options
        if (config.Judge is { } judge)
        {
            if (!string.IsNullOrEmpty(judge.ServerConfig.BaseUrl))
                args.Add($"--judge-url {EscapePs(judge.ServerConfig.BaseUrl)}");
            if (judge.ServerConfig.Model is { Kind: ModelSourceKind.LocalFile } judgeModel && !string.IsNullOrEmpty(judgeModel.FilePath))
                args.Add($"--judge-model-file {EscapePs(judgeModel.FilePath)}");
            else if (judge.ServerConfig.Model is { Kind: ModelSourceKind.HuggingFace } judgeHf && !string.IsNullOrEmpty(judgeHf.HfRepo))
                args.Add($"--judge-hf-repo {EscapePs(judgeHf.HfRepo)}");
            if (!string.IsNullOrEmpty(judge.ServerConfig.ApiKey))
                args.Add($"--judge-api-key {EscapePs(judge.ServerConfig.ApiKey)}");
            if (!string.IsNullOrEmpty(judge.JudgePromptTemplate) && judge.JudgePromptTemplate != "standard")
                args.Add($"--judge-template {EscapePs(judge.JudgePromptTemplate)}");
            if (judge.ScoreMinValue != 0)
                args.Add($"--judge-score-min {judge.ScoreMinValue}");
            if (judge.ScoreMaxValue != 10)
                args.Add($"--judge-score-max {judge.ScoreMaxValue}");
        }

        // Output options
        if (!string.IsNullOrEmpty(config.Run.PipelineName) && config.Run.PipelineName != "CasualQA")
            args.Add($"--pipeline {EscapePs(config.Run.PipelineName)}");
        if (!string.IsNullOrEmpty(config.Run.OutputDirectoryPath) && config.Run.OutputDirectoryPath != "./results")
            args.Add($"--output-dir {EscapePs(config.Run.OutputDirectoryPath)}");
        if (!string.IsNullOrEmpty(config.Run.RunName))
            args.Add($"--run-name {EscapePs(config.Run.RunName)}");

        // Run control
        if (config.Run.MaxConcurrentEvals.HasValue)
            args.Add($"--max-concurrent {config.Run.MaxConcurrentEvals}");
        if (config.Run.ContinueOnEvalFailure == false)
            args.Add("--stop-on-failure");

        // Build the command
        _ = sb.AppendLine("# Run Seevalocal with all settings");

        // PowerShell uses backtick (`) for line continuation, not backslash (\)
        sb.Append("seevalocal");
        if (args.Count > 0)
        {
            _ = sb.AppendLine(" `");
            for (int i = 0; i < args.Count; i++)
            {
                _ = sb.Append($"  {args[i]}");
                // Only add continuation character if this is not the last argument
                _ = i < args.Count - 1 ? sb.AppendLine(" `") : sb.AppendLine();
            }
        }
        else
        {
            _ = sb.AppendLine();
        }

        return sb.ToString();
    }

    // -------------------------------------------------------------------------
    // Escaping helpers
    // -------------------------------------------------------------------------

    private static string EscapeBash(string s)
    {
        return s.Contains(' ') || s.Contains('\'') || s.Contains('"') ? $"'{s.Replace("'", "'\\''")}'" : s;
    }

    private static string EscapePs(string s)
    {
        return s.Contains(' ') || s.Contains('"') ? $"\"{s.Replace("\"", "\"\"")}\"" : s;
    }
}
