// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.
using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Performance", "CA1873:Avoid potentially expensive logging", Justification = "<Pending>", Scope = "member", Target = "~M:Seevalocal.Server.Client.LlamaServerClient.GetAsync``1(System.String,System.Threading.CancellationToken)~System.Threading.Tasks.Task{FluentResults.Result{``0}}")]
[assembly: SuppressMessage("Performance", "CA1873:Avoid potentially expensive logging", Justification = "<Pending>", Scope = "member", Target = "~M:Seevalocal.Server.Client.LlamaServerClient.PostAsync``2(System.String,``0,System.Threading.CancellationToken)~System.Threading.Tasks.Task{FluentResults.Result{``1}}")]
[assembly: SuppressMessage("Performance", "CA1873:Avoid potentially expensive logging", Justification = "<Pending>", Scope = "member", Target = "~M:Seevalocal.Server.Detection.GpuDetector.TryRunToolAsync(System.String,System.String,System.Threading.CancellationToken)~System.Threading.Tasks.Task{System.Boolean}")]
[assembly: SuppressMessage("Performance", "CA1873:Avoid potentially expensive logging", Justification = "<Pending>", Scope = "member", Target = "~M:Seevalocal.Server.Download.LlamaServerDownloader.DownloadAndExtractAsync(Seevalocal.Server.Download.LlamaServerDownloader.GithubAsset,System.String,System.String,System.Threading.CancellationToken)~System.Threading.Tasks.Task{FluentResults.Result{System.String}}")]
[assembly: SuppressMessage("Performance", "CA1873:Avoid potentially expensive logging", Justification = "<Pending>", Scope = "member", Target = "~M:Seevalocal.Server.Download.LlamaServerDownloader.EnsureAvailableAsync(System.String,Seevalocal.Core.Models.GpuKind,System.String,System.Threading.CancellationToken)~System.Threading.Tasks.Task{FluentResults.Result{System.String}}")]
[assembly: SuppressMessage("Performance", "CA1873:Avoid potentially expensive logging", Justification = "<Pending>", Scope = "member", Target = "~M:Seevalocal.Server.Download.LlamaServerDownloader.SelectAsset(System.Collections.Generic.IReadOnlyList{Seevalocal.Server.Download.LlamaServerDownloader.GithubAsset},Seevalocal.Core.Models.GpuKind)~FluentResults.Result{Seevalocal.Server.Download.LlamaServerDownloader.GithubAsset}")]
[assembly: SuppressMessage("Performance", "CA1873:Avoid potentially expensive logging", Justification = "<Pending>", Scope = "member", Target = "~M:Seevalocal.Server.Lifecycle.LlamaServerManager.ConnectExistingAsync(Seevalocal.Core.Models.ServerConfig,System.Threading.CancellationToken)~System.Threading.Tasks.Task{FluentResults.Result{Seevalocal.Server.Models.ServerInfo}}")]
[assembly: SuppressMessage("Performance", "CA1873:Avoid potentially expensive logging", Justification = "<Pending>", Scope = "member", Target = "~M:Seevalocal.Server.Lifecycle.LlamaServerManager.DisposeAsync~System.Threading.Tasks.ValueTask")]
[assembly: SuppressMessage("Performance", "CA1873:Avoid potentially expensive logging", Justification = "<Pending>", Scope = "member", Target = "~M:Seevalocal.Server.Lifecycle.LlamaServerManager.ResolveBinaryPathAsync(Seevalocal.Core.Models.ServerConfig,System.Threading.CancellationToken)~System.Threading.Tasks.Task{FluentResults.Result{System.String}}")]
[assembly: SuppressMessage("Performance", "CA1873:Avoid potentially expensive logging", Justification = "<Pending>", Scope = "member", Target = "~M:Seevalocal.Server.Lifecycle.LlamaServerManager.StartManagedAsync(Seevalocal.Core.Models.ServerConfig,Seevalocal.Core.Models.LlamaServerSettings,System.Threading.CancellationToken)~System.Threading.Tasks.Task{FluentResults.Result{Seevalocal.Server.Models.ServerInfo}}")]
[assembly: SuppressMessage("Performance", "CA1873:Avoid potentially expensive logging", Justification = "<Pending>", Scope = "member", Target = "~M:Seevalocal.Server.Lifecycle.LlamaServerManager.WaitForHealthAsync(System.String,System.Double,System.Threading.CancellationToken)~System.Threading.Tasks.Task{System.Boolean}")]
